import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const contract = readFileSync(
  new URL("../docs/runbooks/remake-shot-edit-contract-v1.md", import.meta.url),
  "utf8",
);

function section(title: string, nextTitle?: string) {
  const start = contract.indexOf(title);
  expect(start).toBeGreaterThanOrEqual(0);
  const end = nextTitle ? contract.indexOf(nextTitle, start + title.length) : contract.length;
  expect(end).toBeGreaterThan(start);
  return contract.slice(start, end);
}

describe("Remake R2 Shot Edit Persistence and Generation Boundary contract", () => {
  it("keeps the Original AI Storyboard immutable and separate from user Drafts", () => {
    const original = section("## 4. Original AI Storyboard contract", "## 5. User Shot Draft contract");
    expect(original).toContain("`v1 original`");
    expect(original).toContain("No `PATCH` or `DELETE` route exists for an Original Shot");
    expect(original).toContain("never silently rebases, repairs or updates the Draft");
    expect(contract).toContain("Editing never updates, replaces or annotates the VLM result row or canonical storyboard payload");
  });

  it("defines the required Shot Draft fields and v1/v2 version boundary", () => {
    const draft = section("## 5. User Shot Draft contract", "## 6. Persistence API proposal");
    for (const field of [
      "shotRef",
      "originalContentHash",
      "editedDescription",
      "editedPrompt",
      "contentVersion",
      "revision",
    ]) {
      expect(draft).toContain(field);
    }
    expect(draft).toContain("`contentVersion=1` means the immutable Original Shot contract");
    expect(draft).toContain("`contentVersion=2` means the user-edit Draft contract");
    expect(draft).toContain("Only these fields are editable in R2");
  });

  it("binds Drafts to a deterministic server-computed Original content hash", () => {
    expect(contract).toContain("`originalContentHash` is generated by the Backend");
    expect(contract).toContain("The proposed algorithm is `SHA-256`");
    expect(contract).toContain("hashContractVersion=remake-original-shot-v1");
    expect(contract).toContain("ordered canonical keyframe assetRef + time pairs");
    expect(contract).toContain("`ORIGINAL_CONTENT_CHANGED`");
  });

  it("requires explicit confirmation and a separate explicit Generate action", () => {
    const boundary = section("## 7. Generation boundary", "## 8. Credit and side-effect protection");
    expect(boundary).toContain("USER_DRAFT_V2_CONFIRMED");
    expect(boundary).toContain("explicit user Generate action");
    expect(boundary).toContain("Draft create/update/autosave -> generation");
    expect(boundary).toContain("Browser-only local state -> generation");
    expect(boundary).toContain('"confirmationRef"');
    expect(boundary).toContain("existing atomic Job/Credit transaction");
    expect(boundary).toContain("metadata-only Outbox");
  });

  it("gives Draft save and confirmation zero Job, Provider, Credit and Billing authority", () => {
    const protection = section("## 8. Credit and side-effect protection", "## 9. Frontend state contract");
    expect(protection).toContain("Create/update/autosave Draft | 0 | 0 | 0 | 0 | 0");
    expect(protection).toContain("Confirm Draft | 0 | 0 | 0 | 0 | 0");
    expect(protection).toContain("Confirmation cannot reserve, hold, debit or refund Credits");
    expect(protection).toContain("rejection occurs before Job/Credit writes");
    expect(protection).toContain("it never causes Browser resubmit or a second debit");
  });

  it("defines idempotency, optimistic concurrency, ownership and fail-closed errors", () => {
    expect(contract).toContain("`Idempotency-Key`");
    expect(contract).toContain("`expectedRevision`");
    expect(contract).toContain("`DRAFT_VERSION_CONFLICT`");
    expect(contract).toContain("`IDEMPOTENCY_CONFLICT`");
    expect(contract).toContain("`CONFIRMATION_SCOPE_MISMATCH`");
    expect(contract).toContain("cross-user");
    expect(contract).toContain("cross-Tenant");
  });

  it("excludes raw VLM, Provider, secret and internal metadata from projections and audit", () => {
    const audit = section("## 11. Audit and privacy", "## 12. Architecture validation matrix");
    expect(contract).toContain("must never include raw VLM response");
    expect(audit).toContain("must not store raw prompt/description");
    expect(audit).toContain("raw VLM output");
    expect(audit).toContain("Provider payload");
    expect(audit).toContain("keyframe URL");
    expect(audit).toContain("secret");
  });

  it("is design-only and publishes the required readiness classification", () => {
    const safety = section("## 14. Candidate safety statement");
    expect(contract).toContain("Status: `DESIGN_ONLY_NOT_PRODUCTION`");
    expect(safety).toContain("Frontend runtime | No");
    expect(safety).toContain("Backend API/runtime | No");
    expect(safety).toContain("Database schema/migration | No");
    expect(safety).toContain("Video Generate/Job/Outbox | No");
    expect(safety).toContain("Provider/Provider Status | No");
    expect(safety).toContain("Credits/refunds/ledger | No");
    expect(safety).toContain("Billing/Stripe/Membership | No");
    expect(safety).toContain("SHOT_EDIT_CONTRACT_READY=YES");
    expect(safety).toContain("ORIGINAL_ANALYSIS_IMMUTABLE=YES");
    expect(safety).toContain("GENERATION_BOUNDARY_READY=YES");
    expect(safety).toContain("CREDIT_PROTECTION_READY=YES");
    expect(safety).toContain("PRODUCTION_CHANGE=NO");
  });
});
